language: node_js
node_js:
 - "11.10.0"
services:
  - MongoDB
before_install:
  - cd application_code
  - npm i -g npm@6.7.0
install:
  - npm install
cache:
  - npm
script:
  - npm run test
notifications:
  slack: nyu-agile-software:04E7Sc8kwphZ6MOgPVlchAMe
